# Generated by Django 4.2.10 on 2024-03-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictweet', '0002_tweet_author_alter_tweet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='name',
        ),
    ]
